---
title: "Part 1 Multiple Linear Regression"
author: "Aaron Kreisberg"
date: "12/1/2020"
output: html_document
---

```{r setup, message = FALSE, error = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(palmerpenguins)
library(GGally)
library(stargazer)
```

```{r, warning = FALSE, message = FALSE, error = FALSE}
penguins %>% 
  ggpairs()
```

```{r, warning = FALSE, message = FALSE, error = FALSE}
penguins %>% 
  select(species, bill_length_mm:body_mass_g) %>% 
  ggpairs(aes(colour = species))
```

## Build a few different models

```{r}
lm1 <- lm(body_mass_g ~ flipper_length_mm + species, data = penguins)

lm2 <- lm(body_mass_g ~ flipper_length_mm + species + sex, data = penguins)

lm3 <- lm(body_mass_g ~ flipper_length_mm + species + sex + bill_length_mm, data = penguins)

lm4 <- lm(body_mass_g ~ flipper_length_mm + species + sex + bill_length_mm + island, data = penguins)

```

```{r}
plot(lm1)

plot(lm2)

plot(lm3)

plot(lm4)

```

## Find AIC value for each model
```{r}
AIC(lm1)
```

```{r}
AIC(lm2)
```

```{r}
AIC(lm3) # Lowest
```

```{r}
AIC(lm4)
```

## Use stargazer package for a table with multiple model outputs

```{r, results = 'asis'}
stargazer(lm1, lm3, lm4, type = "html")
```

## Omitted variable bias - Simpson's paradox

```{r}
ggplot(data = penguins, aes(x = flipper_length_mm, y = bill_depth_mm)) +
  geom_point() +
  geom_smooth(method = "lm")
```

```{r}
ggplot(data = penguins, aes(x = flipper_length_mm,
                            y = bill_depth_mm,
                            group = species)) +
  geom_point(aes(color = species)) +
  geom_smooth(method = "lm")
```

